name: Tel Mond Red Alert
version: "1.0.0"
slug: telmond_alerts
description: Paid add-on. Requires a license passcode from Elisha Design.
startup: application
boot: auto
init: false
host_network: true

options:
  license_passcode: ""

schema:
  license_passcode: str

environment:
  LICENSE_PASSCODE: "!secret license_passcode"
